language: python
sudo: required
dist: trusty
cache:
  directories: [ '$HOME/lxc' ]
  pip: true
env:
  matrix:
  - LXC_DISTRO=debian LXC_RELEASE=jessie
  - LXC_DISTRO=ubuntu LXC_RELEASE=xenial
  - LXC_DISTRO=centos LXC_RELEASE=7
  global:
    secure: T5p6pyD17rpuWq+mwegJDwf12QQsb+ckIlHeCf5mMUk57LBkgUzWN9tcE3/1K70UW7ElQ4zxfASLTIjAUqH023ZiNFUuXqs4QCUeTP8YNBa8xbMeM8MsGRAs4tJWd6TZx/0G7vAJ0uOV/3MFVCsJVtv1aRMpmg4ygavSqQhdiBwdU2NvlfSHNWJ+5t+5Mjpa6T9Mcex6yn1kdomq7ewnl25KERm/Q64/TESdTAG0BdZbX5kCU0PrxGhnMLW4Dzi/EfjclN8HN7ZtldSzJAgSf2x7lFuYMFe7Sloh8i4Ll5MNmUpfPChQUKoQrc3zDbOsfplLFq3arJZZZeeOmRoHJHOL8iuH0JD3+9dcc9m1/DrD6BobVJ8eimcNyEApUqJmqw1B1346VXuB/rIDh9bkikW01bTKFW9dR6skV+Bfl5514QFNKvQxrI5itlO3y8AjbCDsds9e7k2hhmKpaCvjjnkgXHSJfV5nOBpxjuJbk13tpWcLnSxR7P/jF2khYpEG85BomWRjjtpUV+C9WpXrQL/nwv+RIlCfD4d6lyMUhnh1A8wmIJklUtvIUtkeEkM45z9lNDXvcpl1aRqtvn5uX0oFKwkQbZt1w0w8X4yPOE6bnVsr/vvcU3BsC/DpkHlbJQ0LHvjAhkILTOEyLzRpVdHEulOUL5cOPUNUTzUjQ28=
before_cache:
- sudo mkdir $HOME/lxc && sudo tar cf $HOME/lxc/cache.tar /var/cache/lxc/ && sudo chown $USER. $HOME/lxc/cache.tar
install:
- sudo tar xf $HOME/lxc/cache.tar -C / || true
- sudo apt-get install -y expect-dev
- pip install ansible
- ansible --version
- printf '[defaults]\nroles_path=../\ncallback_whitelist=profile_tasks'  >ansible.cfg
- ansible-galaxy install lae.travis-lxc
- ansible-playbook -vvv tests/install.yml
script:
- ansible-playbook tests/test.yml -i tests/inventory --syntax-check
- ansible-playbook tests/test.yml -i tests/inventory
- unbuffer ansible-playbook -vvv tests/test.yml -i tests/inventory >/tmp/idempotency.log
  2>&1
- 'grep -A1 "PLAY RECAP" /tmp/idempotency.log | grep -qP "changed=0.*failed=0" && (echo "Idempotence:
  PASS"; exit 0) || (echo "Idempotence: FAIL"; cat /tmp/idempotency.log; exit 1)'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: KoZ7wRz++oy5UAxV7ux1PjewoskNTP3J4WxpsaDBMFImUaBVXASJI1yf5hiPxbIoqs1gzD8GtbDGm6BIB+iRUuVo1xYp2+5Q0YUozxlwSaZit8uXOfGkEgn48sZFVTGlYCIv8oYtsl+wIeZB1thIhAUxsZYTuh1m73C7GqcFqBTw0EdDBfTTUfF2Hqx+7G59vxyoF9B09Xzu5hierxhjFZ87MuiBwBdp5Du6X2DGbhwMydzzriVSyqxo3SoCNd4PYgewG+5JqkJuWuT8SPAsbGOJJFoz7qtaVKsoBN7Sppl0bWHqe2wlN9mvKfH7b2zdWqH+8zFIJpPAq2fFm5SDjAY8CD2lJg408p3sLjyBtZBZlbJSfF/NKp7QQ1d21u/JzjxDcaHCq7c9hoIQS27J1QvM2pjfceAk3Tu4gg4F1MHcpOaa9szwf/9mXeyN+lo9kZ9q5BIiG9p21DR3CJZ9FkR5jMnfC34ohPx8GY6vLIXB3MVB1tzvZrRXnpuoFJArlS5ZqCZRUDGEGXAUJLd3MRh0k76SznzYnSVqIKQbjCAIs2yw3vJPkpMzBkAnsLwyyYcAYJcr23YeomKGMvC3RvNozfQi08lU5P+IlTNN3Oklo3DVu4AfczMelO1gC2MhoNfi92EdStlmSzdqU8dklCXBglpzpns6AeldDoXy16g=
